name: Publish Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: print secret
        env:
          DEBUG_PASSWORD: ${{ secrets.DOCKER_USERNAME }}
          DEBUG_SECRET_KEY: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo $DEBUG_PASSWORD >> secrets.txt
          echo $DEBUG_SECRET_KEY >> secrets.txt
          cat secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
